### ISSUE TITLE
Bug in PySimulate

### ISSUE THREAD

**Issue by cwsalgado** [JeffersonLab/PyPWA#109]
Traceback from trying to run example amplitude with release-v2.0.0

```
Traceback (most recent call last):
  File "/home/salgado/.local/bin//PySimulate", line 11, in <module>
    load_entry_point('PyPWA', 'console_scripts', 'PySimulate')()
  File "/home/salgado/TESTING/PyPWA/PyPWA/entries/configurator.py", line 87, in py_simulate
    initializer.start(configuration)
  File "/home/salgado/TESTING/PyPWA/PyPWA/core/configurator/start.py", line 141, in start
    self.__process_arguments()
  File "/home/salgado/TESTING/PyPWA/PyPWA/core/configurator/start.py", line 209, in __process_arguments
    self.__run_builder()
  File "/home/salgado/TESTING/PyPWA/PyPWA/core/configurator/start.py", line 214, in __run_builder
    self.__arguments.configuration_location
  File "/home/salgado/TESTING/PyPWA/PyPWA/core/configurator/execute/start.py", line 44, in run
    self.__execute()
  File "/home/salgado/TESTING/PyPWA/PyPWA/core/configurator/execute/start.py", line 55, in __execute
    self.__executor.execute()
  File "/home/salgado/TESTING/PyPWA/PyPWA/core/configurator/execute/_plugin_data.py", line 222, in execute
    program = self.__main.main_program
AttributeError: 'NoneType' object has no attribute 'main_program'
```
Configuration and Amplitude inside zip file.
[RHO.zip](https://github.com/JeffersonLab/PyPWA/files/947934/RHO.zip)

**Comment by Markjonestx** [comment]
Corrected the issues. Please try again, though keep in mind that you can only return one value in your processing_function.
