### ISSUE TITLE
OSError: Missing File and Directory

### ISSUE THREAD

**Issue by lmhare** [JeffersonLab/PyPWA#78]
I was following the PyPWA Manual - Fitting Step-by-Step guide. I was on Step 7. When I attempted to run PWA_GUI I was stopped in the analysis and was given the following:
```
**Exception in Tkinter callback
Traceback (most recent call last):
  File "/u/apps/anaconda/anaconda-2.0.1/lib/python2.7/lib-tk/Tkinter.py", line 1536, in __call__
    return self.func(*args)
  File "./PWA_GUI", line 142, in <lambda>
    btnR0=tk.Button(frame3, text="data", height=2 , width = 10,command= lambda: self.runD(prog,"y"))
  File "./PWA_GUI", line 111, in runD
    sp.call([os.path.join(os.getcwd().strip("GUI"),"scripts","GUI_gamp_main.py"),str(FoS),"data"])
  File "/u/apps/anaconda/anaconda-2.0.1/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/u/apps/anaconda/anaconda-2.0.1/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/u/apps/anaconda/anaconda-2.0.1/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
**
```

**Comment by Markjonestx** [comment]
The solution is to run the the pythonPWA install program from the directory containing your data. ie
```
cd /work/clas/clasg12/lmhare/phi/
./PyPWA-1.1/pythonPWA/batchFarmServices/fitting_install
```
